#cloud-config
# groups:
#   - docker
users:
  - default
#   # the docker service account
#   - name: docker-service
#     groups: docker
# package_upgrade: true
# packages:
#   - apt-transport-https
#   - ca-certificates
#   - curl
#   - gnupg-agent
#   - software-properties-common
runcmd:
  - curl -sSLf https://get.k0s.sh | sudo sh
  - sudo k0s install controller --single
  - sudo k0s start
# power_state:
#   mode: reboot
#   message: Restarting after installing docker & docker-compose'